<?php
//use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_theme().
 */
function fresh_time_theme($existing, $type, $theme, $path) {
  return [
    'similar' => [
      'variables' => [
        'nodes' => [
          'title' => [],
          'url' => [],
        ]
      ]
    ],
    'comments' => [
      'variables' => [
        'comments' => [],
          'subject' => [],
          'body' => [],
          'created' => [],
        ]
      ]
  ];
}

function fresh_time_preprocess_breadcrumb(&$variables) {
$request = \Drupal::request();
    if ($route = $request->attributes->get(\Symfony\Cmf\Component\Routing\RouteObjectInterface::ROUTE_OBJECT)) {
      $text = \Drupal::service('title_resolver')->getTitle($request, $route);
    }
    if ($variables['breadcrumb']) {
      $variables['breadcrumb'][] = [
        'text' => $text
      ];
      $variables['#cache']['contexts'][] = 'url.path';
    }
}